name: Update Lambda
on:
  push
jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - uses: stcalica/update-lambda
        with:
          package: lambda.zip
          function-name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}