name: deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x]
    steps:
      - name: zip lambda code
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r lambda.zip lambda
